services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:C1C10oeDJQog1DPsD6+7ftZqglbDlO++sgIveo7yMGc=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=books_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db
    ports:
      - "9001:9001"

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80"
      
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
